config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  root to: 'top#show'

  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/user/:id', to: redirect('/users/')
  end
  resources :users, only: [:index, :show]
  resources :messages, only: :create
  resources :private_chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :private_chat
end

app/models/private_chat.rb
class PrivateChat < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :private_chat   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    "/user/#{current_user.id}"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.private_chat_id = 4
    if @message.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/private_chats_controller.rb
class PrivateChatsController < ApplicationController
  def show
    if PrivateChat.find_by(id: params[:id]).present?
      @private_chat = PrivateChat.find(params[:id])
      if @private_chat.user_1_id == current_user.id
        @user_name = User.find(@private_chat.user_2_id).name
      elsif @private_chat.user_2_id == current_user.id
        @user_name = User.find(@private_chat.user_1_id).name
      end
      @messages = Message.where(private_chat_id: params[:id])
    else
      redirect_to users_path
    end
  end

  def create
    a = PrivateChat.find_by(user_1_id: params[:user_1_id], user_2_id: params[:user_2_id])
    b = PrivateChat.find_by(user_2_id: params[:user_1_id], user_1_id: params[:user_2_id])
    if a.present?
      redirect_to action: 'show', id: a.id
    elsif b.present?
      redirect_to action: 'show', id: b.id
    else
      @private_chat = PrivateChat.new
      @private_chat.user_1_id = params[:user_1_id]
      @private_chat.user_2_id = params[:user_2_id]
      if @private_chat.save
        redirect_to action: 'show', id: @private_chat.id
      else
        redirect_back(fallback_location: root_path)
      end
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def show
    @messages = Message.all
    @message = Message.new
    if user_signed_in?
      @user_name = current_user.name
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def detail
    @user = User.find_by(id: params[:id])
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/private_chats_helper.rb
module PrivateChatsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatOnyadol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/private_chats/show.html.erb
<% if user_signed_in? %>
  <div id="your_container">

      <!-- チャットの外側部分① -->
      <div id="bms_messages_container">
          <!-- ヘッダー部分② -->
          <div id="bms_chat_header">
              <!--ステータス-->
              <div id="bms_chat_user_status">
                  <!--ステータスアイコン-->
                  <div id="bms_status_icon">●</div>
                  <!--ユーザー名-->
                  <div id="bms_chat_user_name"><%= @user_name %>とのトーク</div>
              </div>
          </div>

          <!-- タイムライン部分③ -->
      <div id="bms_messages">

          <% @messages.each do |message| %>
            <% if message.user.id == current_user.id %>
              <% position = "bms_right" %>
            <% else %>
              <% position = "bms_left" %>
            <% end %>
            <div class="bms_message <%= position %>">
              <div class="bms_message_box">
                <div class="bms_message_content">
                  <span><%= message.user.name %>:</span>
                  <div class="bms_message_text"><%= message.content %></div>
                </div>
              </div>
            </div>
            <div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->
          <% end %>

          <!-- テキストボックス、送信ボタン④ -->
      </div>
      <div id="bms_send">
        <form>
          <input id="chat-form" type="text" data-behavior="chat_post" class="bms_send_message">
          <input id="user-id-value" type="hidden" value="<%= current_user.id %>">
          <input id="user-name-value" type="hidden" value="<%= current_user.name %>">
          <input id="chat-id-value" type="hidden" value="<%= @private_chat.id %>">
        </form>
      </div>
  </div>
<% end %>

<script type="text/javascript">
  window.scrollTo(0,document.body.scrollHeight);
</script>

app/views/top/show.html.erb
<h1>ChatRoom</h1>

<% if user_signed_in? %>
  <div id="your_container">

      <!-- チャットの外側部分① -->
      <div id="bms_messages_container">
          <!-- ヘッダー部分② -->
          <div id="bms_chat_header">
              <!--ステータス-->
              <div id="bms_chat_user_status">
                  <!--ステータスアイコン-->
                  <div id="bms_status_icon">●</div>
                  <!--ユーザー名-->
                  <div id="bms_chat_user_name"><%= current_user.name %></div>
              </div>
          </div>

          <!-- タイムライン部分③ -->
      <div id="bms_messages">

          <% @messages.each do |message| %>
            <% if message.user.id == current_user.id %>
              <% position = "bms_right" %>
            <% else %>
              <% position = "bms_left" %>
            <% end %>
            <div class="bms_message <%= position %>">
              <div class="bms_message_box">
                <div class="bms_message_content">
                  <div class="bms_message_text"><%= message.content %></div>
                </div>
              </div>
            </div>
            <div class="bms_clear"></div><!-- 回り込みを解除（スタイルはcssで充てる） -->
          <% end %>

          <!-- テキストボックス、送信ボタン④ -->
      </div>
      <div id="bms_send">
        <form>
          <input id="chat-form" type="text" data-behavior="chat_post" class="bms_send_message">
          <input id="user-id-value" type="hidden" value="<%= current_user.id %>">
        </form>
      </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <ul>
    <li>
      <%= user.name %>
      <% unless user.id == current_user.id %>
        <% if PrivateChat.find_by(user_1_id: current_user.id, user_2_id: user.id) || PrivateChat.find_by(user_2_id: current_user.id, user_1_id: user.id) %>
          <% a = PrivateChat.find_by(user_1_id: current_user.id, user_2_id: user.id) %>
          <% b = PrivateChat.find_by(user_2_id: current_user.id, user_1_id: user.id) %>
          <% if a.present? %>
            <% chat_room_id = a.id %>
          <% elsif b.present? %>
            <% chat_room_id = b.id %>
          <% end %>
          <%= link_to "トークルームへ行く", private_chat_path(chat_room_id) %>
        <% else %>
          <%= link_to "トークを始める", private_chats_path(user_1_id: current_user.id, user_2_id: user.id), method: :post %>
        <% end %>
      <% end %>
    </li>
  </ul>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>